kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: rsyslogd
  namespace: openshift-logging
spec:
  selector:
    matchLabels:
      app: rsyslogd
  template:
    metadata:
      labels:
        app: rsyslogd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: rsyslogd
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: LOGSERVER
            value: 'logs.example.com' # Change this to match your environment
          - name: SYSLOGD_OPTIONS
            value: '-f /config/rsyslog.conf'
        image: registry.redhat.io/rhel8/rsyslog
        command: ["/usr/sbin/rsyslogd","-n","-f","/config/rsyslog.conf"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: rsyslogd-config
          readOnly: true
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/tmp
          name: vartmp
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      securityContext: {}
      serviceAccount: logcollector
      serviceAccountName: logcollector
      volumes:
      - configMap:
          defaultMode: 420
          name: rsyslogd-config
        name: rsyslogd-config
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/tmp
          type: ""
        name: vartmp
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
